services:
  rccremote: &rcc
    build:
      context: .
      dockerfile: Dockerfile-rcc
    container_name: rccremote
    command: rccremote
    volumes:
      - ./entrypoint-rcc.sh:/entrypoint.sh
      - ./robots:/robots
      - ./certs:/etc/certs:ro
    networks:
      - app-network

  # only uncomment for testing
  rcc:
    <<: *rcc
    container_name: rcc
    command: rcc
    volumes:
      - ./entrypoint-rcc.sh:/entrypoint.sh
      - ./robots:/robots
      - ./certs:/etc/certs:ro
      - ./config/rcc-profile-cabundle.yaml.template:/rcc-profile-cabundle.yaml.template
    environment:
      - RCC_REMOTE_ORIGIN=https://rccremote.local:${NGINX_PORT:-443}

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - rccremote
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    networks:
      app-network:
        aliases:
          - rccremote.local

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
