services:
  rccremote: &rcc
    build:
      context: .
      dockerfile: Dockerfile-rcc
    container_name: rccremote
    command: rccremote
    volumes:
      - ./scripts:/scripts
      - ./robots:/robots
      - ./certs:/etc/certs:ro
      - robocorp_data:/opt/robocorp
    networks:
      - app-network

  # only uncomment for testing
  # rcc:
  #   <<: *rcc
  #   container_name: rcc
  #   command: rcc
  #   volumes:
  #     - ./scripts:/scripts
  #     - ./robots:/robots
  #     - ./certs:/etc/certs:ro
  #     - ./config/rcc-profiles.d:/etc/rcc-profiles.d:ro
  #   environment:
  #     - RCC_REMOTE_ORIGIN=https://${SERVER_NAME}:${NGINX_PORT:-443}

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - rccremote
    volumes:
      - ./config/nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./certs:/etc/nginx/certs
      - ./scripts/entrypoint-nginx.sh:/docker-entrypoint.d/entrypoint-nginx.sh
      - ./scripts/openssl.cnf.template:/openssl.cnf.template
    ports:
      - "443:443"
    environment:
      - SERVER_NAME=${SERVER_NAME}
    networks:
      app-network:
        aliases:
          - ${SERVER_NAME}

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
  robocorp_data:
