services:
  rccremote:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rccremote
    volumes:
      - ./data:/data
      - ./certs:/etc/certs:ro
    networks:
      - app-network
  # rcc:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: rcc
  #   volumes:
  #     - ./data:/data
  #     - ./certs:/etc/certs:ro
  #   networks:
  #     - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - rccremote
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local
