name: ssl-noverify
description: disabled SSL verification

settings: 
  certificates:
    verify-ssl: false
    ssl-no-revoke: false

  meta:
    name: ssl-noverify
    description: disabled SSL verification
    source: manual
    version: 2024.10
